---
name: Flickr-Upload-Dopplr
version: 0.1
author:
  - 'Aaron Straup Cope <ascope@cpan.org>'
abstract: Flickr::Upload subclass to assign location information using Dopplr
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Flickr::Upload: '>= 1.25'
  Image::Info: 0
  Net::Dopplr: '>= 0.2'
build_requires:
  Test::Simple: '>= 0.47'
provides:
  FUDException:
    file: lib/Flickr/Upload/Dopplr.pm
  Flickr::Upload::Dopplr:
    file: lib/Flickr/Upload/Dopplr.pm
    version: 0.1
  FlickrAPIException:
    file: lib/Flickr/Upload/Dopplr.pm
  FlickrUploadException:
    file: lib/Flickr/Upload/Dopplr.pm
  NetDopplrException:
    file: lib/Flickr/Upload/Dopplr.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
